# Generated by Django 3.2.6 on 2021-09-08 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('customer_name', models.CharField(max_length=255, null=True, unique=True)),
                ('date_of_birth', models.CharField(max_length=20)),
                ('phone_numner', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
                ('province', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('ward', models.CharField(max_length=255)),
                ('bank_name', models.CharField(max_length=255, null=True, unique=True)),
                ('bank_number', models.IntegerField()),
                ('bank_provine', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
