# Generated by Django 3.2.6 on 2021-09-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='bank_username',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
