# Generated by Django 3.2.6 on 2021-09-11 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customer_bank_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='bank_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='bank_username',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
