# Generated by Django 3.2.6 on 2021-09-13 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210911_2133'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShipOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_phonenumber', models.CharField(max_length=15)),
                ('customer_name', models.CharField(blank=True, max_length=255)),
                ('detail_address', models.CharField(blank=True, max_length=255)),
                ('product_name', models.CharField(blank=True, max_length=255)),
                ('product_weight', models.DecimalField(decimal_places=2, max_digits=8)),
                ('product_quantity', models.IntegerField()),
                ('ship_option', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.shipoptions')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_status', to='api.orderstatus')),
            ],
        ),
    ]
