# Generated by Django 3.2.6 on 2021-09-14 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_order_orderstatus_shipoptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
