# Generated by Django 3.2.6 on 2021-09-14 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_order_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product_image',
        ),
    ]
