# Generated by Django 3.2.6 on 2021-09-14 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_order_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cast',
            field=models.IntegerField(default=20000),
            preserve_default=False,
        ),
    ]
