# Generated by Django 3.2.6 on 2021-09-14 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_order_cast'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
