# Generated by Django 3.2.6 on 2021-09-19 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20210918_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipoptions',
            name='fee',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
