# Generated by Django 3.2.6 on 2021-10-06 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_instanceaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=12)),
                ('email', models.CharField(max_length=100)),
                ('cmnd', models.CharField(max_length=12)),
                ('age', models.IntegerField(default=18)),
                ('DriverLicense', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
