# Generated by Django 3.2.6 on 2021-10-06 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_order_driver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='DriverLicense',
            new_name='driverLicense',
        ),
    ]
