# Generated by Django 3.2.6 on 2021-10-14 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_order_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='isRecieved',
            field=models.BooleanField(default=False),
        ),
    ]
