# Generated by Django 3.2.6 on 2021-10-14 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_order_isrecieved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='paid',
        ),
    ]
