# Generated by Django 3.2.6 on 2021-10-14 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_order_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='isDone',
            field=models.BooleanField(default=False),
        ),
    ]
