# Generated by Django 3.2.6 on 2021-11-28 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_customer_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='product-image/'),
        ),
    ]
