# Generated by Django 3.2.6 on 2021-12-02 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_driver_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_image',
            field=models.ImageField(blank=True, upload_to='product-image/'),
        ),
    ]
