# Generated by Django 3.2.6 on 2021-12-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20211206_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_numner',
            field=models.CharField(max_length=20),
        ),
    ]
