import {StyleSheet} from 'react-native';
import {headerFontSize, appFontSize, greyColor} from '../../contants';

const styles = StyleSheet.create({
  container: {
    height: 70,
    width: '100%',
    flexDirection: 'row',
    backgroundColor: '#ff7733',
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  userInformationText: {
    fontSize: headerFontSize,
    fontWeight: 'bold',
    marginLeft: 10,
  },
  headerWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFF',
    height: 65,
  },
  nameWrapper: {
    fontSize: 22,
    color: '#000',
  },
  backIcon: {
    width: 25,
    height: 25,
  },
  bankingInforWrapper: {
    height: 240,
    flexDirection: 'column',
    width: '92%',
    backgroundColor: '#FFF',
    alignSelf: 'center',
    marginTop: 20,
    borderRadius: 10,
  },
  basicInforDetail: {
    height: 50,
    flexDirection: 'row',
    paddingLeft: 10,
    alignItems: 'center',
    borderBottomWidth: 0.5,
  },
  basicInforImage: {
    height: 30,
    width: 30,
  },
  basicInforText: {
    fontSize: 17,
    marginLeft: 10,
  },
  inputText: {
    marginLeft: 10,
    fontSize: appFontSize,
  },
  bankingEditInforWrapper: {
    height: 400,
    flexDirection: 'column',
    width: '92%',
    backgroundColor: '#FFF',
    alignSelf: 'center',
    marginTop: 20,
    borderRadius: 10,
  },
  editBakingDetailWrapper: {
    flexDirection: 'column',
    justifyContent: 'center',
    paddingLeft: 10,
    paddingRight: 10,
    paddingTop: 10,
  },
  bankingEditInput: {
    fontSize: 17,
    borderWidth: 0.3,
    borderRadius: 10,
    marginTop: 5,
    height: 40,
    paddingLeft: 10,
  },
  banksPicker: {
    borderWidth: 0.3,
    borderColor: greyColor,
  },
  khoDoInforDetail: {
    height: 50,
    padding: 10,
    borderBottomWidth: 0.8,
    borderBottomColor: greyColor,
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    width: 385,
  },
  locationEditWrapper: {
    height: 80,
    padding: 10,
    borderBottomWidth: 0.8,
    borderBottomColor: greyColor,
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    width: 385,
  },
  xIconStyle: {
    height: 20,
    width: 20,
  },
  modalLocationEditDetailWrapper: {
    width: '90%',
    borderBottomWidth: 0.8,
    borderBottomColor: greyColor,
    flexDirection: 'row',
    alignSelf: 'center',
  },
  btnSaveLocation: {
    width: '92%',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    height: 40,
    backgroundColor: '#ff7733',
    marginTop: 10,
    borderRadius: 10,
  },
  btnSave: {
    width: '92%',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    height: 40,
    backgroundColor: '#ff7733',
    marginTop: 10,
    borderRadius: 10,
  },
  btnBankEdit: {
    backgroundColor: '#E0E0E0',
    height: 40,
    width: 380,
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingLeft: 10,
    paddingRight: 10,
    flexDirection: 'row',
  },
  basicInforWrapper: {
    backgroundColor: '#E0E0E0',
    height: 40,
    width: 380,
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingLeft: 10,
    paddingRight: 10,
    flexDirection: 'row',
  },
  locaInforContainer: {
    flexDirection: 'column',
    alignItems: 'center',
    marginLeft: 10,
    marginTop: 10,
    marginRight: 10,
    borderWidth: 0.8,
    borderColor: greyColor,
    borderRadius: 10,
  },
  addressTitleWrapper: {
    backgroundColor: greyColor,
    flexDirection: 'row',
    width: '100%',
    justifyContent: 'flex-start',
    height: 45,
    padding: 10,
  },
  font17: {
    fontSize: 17,
  },
  btnBankEditedSave: {
    width: '92%',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    height: 40,
    backgroundColor: '#ff7733',
    marginTop: 10,
    borderRadius: 10,
  },
  pickerWrapper: {
    borderWidth: 0.3,
    borderColor: greyColor,
    marginTop: 5,
    borderRadius: 10,
  },
});

export default styles;
